"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "flights",
      [
        {
          id: 1,
          flight_number: "JOG-2501",
          departure_time: "13:00",
          arrival_time: "15:00",
          departure_date: "2023-07-08",
          arrival_date: "2023-07-08",
          departure_location: "Denpasar",
          arrival_location: "Yogyakarta",
          from_id: "DPS",
          to_id: "JOG",
          airline: "Lion Air",
          type_of_flight: "OneWay",
        },

        {
          id: 2,
          flight_number: "MES-7701",
          departure_time: "06:00",
          arrival_time: "09:45",
          departure_date: "2023-07-08",
          arrival_date: "2023-07-08",
          departure_location: "Jakarta",
          arrival_location: "Palembang",
          from_id: "CGK",
          to_id: "MES",
          airline: "Citilink",
          type_of_flight: "OneWay",
        },

        {
          id: 3,
          flight_number: "UPG-1001",
          departure_time: "10:00",
          arrival_time: "12:00",
          departure_date: "2023-07-09",
          arrival_date: "2023-07-09",
          departure_location: "Bandung",
          arrival_location: "Makassar",
          from_id: "BDO",
          to_id: "UPG",
          airline: "Batik Air",
          type_of_flight: "OneWay",
        },

        {
          id: 4,
          flight_number: "CGK-1601",
          departure_time: "06:00",
          arrival_time: "10:30",
          departure_date: "2023-07-10",
          arrival_date: "2023-07-10",
          departure_location: "Batam",
          arrival_location: "Jakarta",
          from_id: "BTH",
          to_id: "CGK",
          airline: "Lion Air",
          type_of_flight: "OneWay",
        },

        {
          id: 5,
          flight_number: "JOG-1002",
          departure_time: "13:00",
          arrival_time: "15:00",
          departure_date: "2023-07-10",
          arrival_date: "2023-07-10",
          departure_location: "Jakarta",
          arrival_location: "Yogyakarta",
          from_id: "CGK",
          to_id: "JOG",
          airline: "Batik Air",
          type_of_flight: "OneWay",
        },

        {
          id: 6,
          flight_number: "DPS-1901",
          departure_time: "13:00",
          arrival_time: "17:00",
          departure_date: "2023-07-10",
          arrival_date: "2023-07-10",
          departure_location: "Surabaya",
          arrival_location: "Denpasar",
          from_id: "SUB",
          to_id: "DPS",
          airline: "Air Asia",
          type_of_flight: "OneWay",
        },

        {
          id: 7,
          flight_number: "BTH-203",
          departure_time: "13:00",
          arrival_time: "15:00",
          departure_date: "2023-07-11",
          arrival_date: "2023-07-11",
          departure_location: "Makassar",
          arrival_location: "Batam",
          from_id: "UPG",
          to_id: "BTH",
          airline: "Lion Air",
          type_of_flight: "OneWay",
        },

        {
          id: 8,
          flight_number: "MDC-1001",
          departure_time: "20:00",
          arrival_time: "21:10",
          departure_date: "2023-07-09",
          arrival_date: "2023-07-09",
          departure_location: "Pekanbaru",
          arrival_location: "Manado",
          from_id: "PKU",
          to_id: "MDC",
          airline: "Garuda Indonesia",
          type_of_flight: "OneWay",
        },

        {
          id: 9,
          flight_number: "KOE-1201",
          departure_time: "15:00",
          arrival_time: "17:30",
          departure_date: "2023-07-11",
          arrival_date: "2023-07-11",
          departure_location: "Denpasar",
          arrival_location: "Kupang",
          from_id: "DPS",
          to_id: "KOE",
          airline: "Super Air Jet",
          type_of_flight: "OneWay",
        },

        {
          id: 10,
          flight_number: "BTJ-1001",
          departure_time: "10:00",
          arrival_time: "12:00",
          departure_date: "2023-07-08",
          arrival_date: "2023-07-08",
          departure_location: "Surabaya",
          arrival_location: "Banda Aceh",
          from_id: "SUB",
          to_id: "BTJ",
          airline: "Citilink",
          type_of_flight: "OneWay",
        },

        {
          id: 11,
          flight_number: "DPS-1002",
          departure_time: "20:00",
          arrival_time: "22:00",
          departure_date: "2023-07-08",
          arrival_date: "2023-07-08",
          departure_location: "Surabaya",
          arrival_location: "Denpasar",
          from_id: "SUB",
          to_id: "DPS",
          airline: "Batik Air",
          type_of_flight: "OneWay",
        },

        {
          id: 12,
          flight_number: "BTJ-1202",
          departure_time: "11:45",
          arrival_time: "14:30",
          departure_date: "2023-07-12",
          arrival_date: "2023-07-12",
          departure_location: "Balikpapan",
          arrival_location: "Banda Aceh",
          from_id: "BPN",
          to_id: "BTJ",
          airline: "Lion Air",
          type_of_flight: "OneWay",
        },

        {
          id: 13,
          flight_number: "CGK-1003",
          departure_time: "10:00",
          arrival_time: "12:00",
          departure_date: "2023-07-12",
          arrival_date: "2023-07-12",
          departure_location: "Batam",
          arrival_location: "Jakarta",
          from_id: "BTH",
          to_id: "CGK",
          airline: "Batik Air",
          type_of_flight: "OneWay",
        },

        {
          id: 14,
          flight_number: "BTJ-0201",
          departure_time: "06:50",
          arrival_time: "10:30",
          departure_date: "2023-07-11",
          arrival_date: "2023-07-11",
          departure_location: "Surabaya",
          arrival_location: "Banda Aceh",
          from_id: "SUB",
          to_id: "BTJ",
          airline: "Super Air jet",
          type_of_flight: "OneWay",
        },

        {
          id: 15,
          flight_number: "BDO-1202",
          departure_time: "11:40",
          arrival_time: "14:40",
          departure_date: "2023-07-08",
          arrival_date: "2023-07-08",
          departure_location: "Semarang",
          arrival_location: "Bandung",
          from_id: "SRG",
          to_id: "BDO",
          airline: "Garuda Indonesia",
          type_of_flight: "OneWay",
        },

        {
          id: 16,
          flight_number: "BDJ-1202",
          departure_time: "11:00",
          arrival_time: "14:10",
          departure_date: "2023-07-12",
          arrival_date: "2023-07-12",
          departure_location: "Surabaya",
          arrival_location: "Banjarmasin",
          from_id: "SUB",
          to_id: "BDJ",
          airline: "Super Air jet",
          type_of_flight: "OneWay",
        },

        {
          id: 17,
          flight_number: "SUB-0201",
          departure_time: "06:50",
          arrival_time: "10:35",
          departure_date: "2023-07-08",
          arrival_date: "2023-07-08",
          departure_location: "Denpasar",
          arrival_location: "Surabaya",
          from_id: "DPS",
          to_id: "SUB",
          airline: "Batik Air",
          type_of_flight: "OneWay",
        },

        {
          id: 18,
          flight_number: "MDC-0201",
          departure_time: "07:00",
          arrival_time: "10:50",
          departure_date: "2023-07-08",
          arrival_date: "2023-07-08",
          departure_location: "Pekanbaru",
          arrival_location: "Manado",
          from_id: "PKU",
          to_id: "MDC",
          airline: "Garuda Indonesia",
          type_of_flight: "OneWay",
        },

        {
          id: 19,
          flight_number: "BDO-0201",
          departure_time: "06:20",
          arrival_time: "10:40",
          departure_date: "2023-07-07",
          arrival_date: "2023-07-07",
          departure_location: "Semarang",
          arrival_location: "Bandung",
          from_id: "SRG",
          to_id: "BDO",
          airline: "Super Air jet",
          type_of_flight: "OneWay",
        },

        {
          id: 20,
          flight_number: "JKT-1122",
          departure_time: "21:00",
          arrival_time: "22:30",
          departure_date: "2023-07-08",
          arrival_date: "2023-07-08",
          departure_location: "Surabaya",
          arrival_location: "Jakarta",
          from_id: "SUB",
          to_id: "JKT",
          airline: "Airbus A380",
          type_of_flight: "OneWay",
        },

        {
          id: 21,
          flight_number: "JKT-1302",
          departure_time: "21:30",
          arrival_time: "23:00",
          departure_date: "2023-07-08",
          arrival_date: "2023-07-08",
          departure_location: "Surabaya",
          arrival_location: "Jakarta",
          from_id: "SUB",
          to_id: "JKT",
          airline: "Garuda Indonesia",
          type_of_flight: "OneWay",
        },

        {
          id: 22,
          flight_number: "JKT-1398",
          departure_time: "19:00",
          arrival_time: "20:30",
          departure_date: "2023-07-08",
          arrival_date: "2023-07-08",
          departure_location: "Surabaya",
          arrival_location: "Jakarta",
          from_id: "SUB",
          to_id: "JKT",
          airline: "Batik Air",
          type_of_flight: "OneWay",
        },

        {
          id: 23,
          flight_number: "JKT-1358",
          departure_time: "22:10",
          arrival_time: "23:40",
          departure_date: "2023-07-08",
          arrival_date: "2023-07-08",
          departure_location: "Surabaya",
          arrival_location: "Jakarta",
          from_id: "SUB",
          to_id: "JKT",
          airline: "Lion Air",
          type_of_flight: "OneWay",
        },

        {
          id: 24,
          flight_number: "JKT-2358",
          departure_time: "18:00",
          arrival_time: "19:30",
          departure_date: "2023-07-09",
          arrival_date: "2023-07-09",
          departure_location: "Surabaya",
          arrival_location: "Jakarta",
          from_id: "SUB",
          to_id: "JKT",
          airline: "Lion Air",
          type_of_flight: "OneWay",
        },

        {
          id: 25,
          flight_number: "JKT-9258",
          departure_time: "19:00",
          arrival_time: "17:30",
          departure_date: "2023-07-10",
          arrival_date: "2023-07-10",
          departure_location: "Surabaya",
          arrival_location: "Jakarta",
          from_id: "SUB",
          to_id: "JKT",
          airline: "Lion Air",
          type_of_flight: "OneWay",
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("flights", null, {});
  },
};
